apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          resources:
            limits:
              cpu: "500m"
              memory: "2000Mi"
            requests:
              cpu: "100m"
              memory: "1000Mi"

